### ISSUE TITLE
reverse a string in javascript

### ISSUE THREAD

**Issue by abhishekrajput-web** [PratikshaChuryaA/Hactoberfest-2024#14]
I kindly request you to review and allow me to contribute this question as part of Hacktoberfest 2024. I am excited to contribute to this project and would appreciate any feedback.

**Comment by abhishekrajput-web** [comment]
hello PratikshaChuryaA, can you please add hacktoberfest-accepted label in the labels, because without this label it is not shown my contribution in gihtub hactoberfest profile

**Comment by abhishekrajput-web** [comment]
hello PratikshaChuryaA, can you please add hacktoberfest and hacktoberfest-accepted tags and labels in your repository because I am not able to see my contribution in hactoberfest because according to github hactoberfest guidelines when anyone make PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label. i am showing you my github hactoberfest pic. it says  Repository Not Participating ?
![hactoberfest 2024](https://github.com/user-attachments/assets/b0c6deea-3a18-4783-9e56-faafce39ade2)

please make some changes and let me know what is the further step to contribute in github hactoberfest 2024

**Comment by Gitwithsuman** [comment]
i have also same problem , is is showing this, what is the solution of it , do u know?

**Comment by PratikshaChuryaA** [comment]
![Screenshot (189)](https://github.com/user-attachments/assets/e925a797-392a-4f28-ad0b-638ee7a1903a)
I am so sorry for this @abhishekrajput-web and @Gitwithsuman , but i am not finding any solution as you can see i have already added the necessary tags. Please let me know if you find any solution. Better contribute to other repositories as well.

**Comment by PratikshaChuryaA** [comment]
Please let me know if you see any changes in your hactoberfest website!
