### ISSUE TITLE
Tail Recursive Reverse

### ISSUE THREAD

**Issue by Gitwithsuman** [PratikshaChuryaA/Hactoberfest-2024#22]
Tail recursion is a form of recursion where the recursive call is the last operation in the function. You can implement tail recursion for reversing the linked list and explain its benefits in terms of space optimization and  i want to add this functionality please assign me to do this and please give the tag of **hactoberfest**

**Comment by Gitwithsuman** [comment]
hi , Pratiksha can u add the hactoberfest accepted level , because it's showing that the repo is not participating and if any other solution there please let me know.

**Comment by PratikshaChuryaA** [comment]
Hi Suman, i have added all the tags necessary dont know why its happening like that. So sorry!

**Comment by Gitwithsuman** [comment]
Ok , no problem,, thanks 🙏, can I create a new issue and give a pull
request to you

**Comment by PratikshaChuryaA** [comment]
Definitely you can! please let me know the status then..
