### ISSUE TITLE
Factorial (In Java)

### ISSUE THREAD

**Issue by Mukta64Chaudhari** [PratikshaChuryaA/Hactoberfest-2024#7]
Factorial algorithm in JAVA.

**Comment by Mukta64Chaudhari** [comment]
Hi @PratikshaChuryaA, I am interested in working on this issue. Can you please assign it to me?
Thanks!

**Comment by Mukta64Chaudhari** [comment]
@PratikshaChuryaA Hactoberfest website is saying that this repository is not participating in hacktoberfest.
Can you please add hactoberfest label to this repo.

**Comment by PratikshaChuryaA** [comment]
I have already added it.
