### ISSUE TITLE
Reverse Linked List - C language 

### ISSUE THREAD

**Issue by HetuKariya** [PratikshaChuryaA/Hactoberfest-2024#8]
I want to solve this problem and add it to your repository as I am a beginner in open source contribution please assign me this question.

**Comment by Gitwithsuman** [comment]
hi pratiksha , i want to contribute in Reverse Linked List that is "Tail Recursive Reverse" please assign me to add this functionality, i am beginer of open source contribution ,i am creating issue please merge it and give the tag of hactoberfest........

**Comment by HKSINGHTHAKUR** [comment]
Hii @PratikshaChuryaA 
I kindly request you to assign me this issue under hactoberfest 2024 with it's tag.
looking forward to do it.
